config/routes.rb
AAAWebsite::Application.routes.draw do

  root :to => 'aaa_core#index'
  match '/events', :to => 'aaa_core#events'
  match '/shop', :to => 'aaa_core#shop'
  match '/discussion', :to => 'aaa_core#discussion'
end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
  	@title = "Home"
  end

  def events
  	@title = "Events"
  end

  def shop
  	@title = "Shop"
  end

  def discussion
  	@title = "Discussion Forum"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Return a title on a per-page basis.
	def title
		base_title = "Freemans Digital Consultancy"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<h1>AaaCore#index</h1>
<p>Find me in app/views/aaa_core/index.html.erb</p>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
&copy; <%= Time.now.year %> Freemans Digital Consultancy
</footer>

app/views/layouts/_header.html.erb
<header>
<h1>Freemans Digital Consultancy</h1>
<h2>We combine strategy, design and technology to create succefull digital experiencies</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Events", events_path %></li>
		<li><%= link_to "Discussion", discussion_path %></li>
		<li><%= link_to "Shop", shop_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

		<%= render 'layouts/header' %>
		<%= render 'layouts/navigation' %>


<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>